/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/
*/
import Link from "next/link"

export function Navbar() {
  return (
    <header className="bg-primary text-primary-foreground py-4 px-6 shadow-sm">
      <div className="mx-auto flex items-center justify-between">
        <Link href="#" className="text-xl font-bold" prefetch={false}>
          Unturned ID Viewer
        </Link>
        <nav className="flex items-center space-x-4">
          <Link href="#" className="hover:underline" prefetch={false}>
            Vanilla IDs
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Buak IDs
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            A6 Polaris IDs
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Escalation IDs
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Arid IDs
          </Link>
          <Link href="#" className="hover:underline" prefetch={false}>
            Elver IDs
          </Link>
        </nav>
      </div>
    </header>
  )
}
