/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/
*/
import Link from "next/link"

// TODO: Factor out links to a JSON array

export function SubNavbar() {
  return (
    <div className="bg-muted py-4 px-6 border-b">
        <div className="mx-auto flex items-center space-x-4">
          <Link href="#" className="text-primary hover:underline" prefetch={false}>
            All IDs
          </Link>
          <Link href="#" className="text-primary hover:underline" prefetch={false}>
            Vehicle IDs
          </Link>
        </div>
      </div>
  )
}
